name: Release package to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          path: sdk
      - uses: actions/checkout@v4
        # ensure that a publication only occurs when a new release is created:
        if: ${{ steps.release.outputs.releases_created }}
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('bun.lockb', 'bunfig.toml') }}
        if: ${{ steps.release.outputs.releases_created }}
      - name: Install dependencies
        run: bun install
        if: ${{ steps.release.outputs.releases_created }}
      - name: Build package
        run: bun run build
        if: ${{ steps.release.outputs.releases_created }}
      - name: Publish package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.releases_created }}
